### ISSUE TITLE
Run everything locally 

### ISSUE THREAD

**Issue by daler-rahimov** [Textualize/textual-web#26]
Hello, I have a quick question. Is it possible to run everything locally instead of making connection to https://textual-web.io/ ? It's a bit concerning to give access to your terminal over the internet.

**Comment by daler-rahimov** [comment]
found the answer in discord, it would be SaaS for near future  https://discord.com/channels/1026214085173461072/1033755627048153092/1153621845552136302

**Comment by patha454** [comment]
Quick note: The author has since released https://github.com/Textualize/textual-serve, which is a locally hosted version.
