### ISSUE TITLE
API for emulating stdin/stdout in Textual App

### ISSUE THREAD

**Issue by davidbrochart** [Textualize/textual-web#33]
It seems that `textual-web` launches each Textual application in a subprocess, and interacts with it through `stdin`/`stdout`. I was wondering if a Textual `App` could have an API that would emulate `stdin`/`stdout`, for instance a registered callback that would be called each time the app writes to `stdout`, and a function to write to the app's `stdin`.
I'm asking because I'd like to do something similar to `textual-web` but with everything in-process. I tried [redirect_stdout](https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stdout) but it doesn't seem to work.

**Comment by willmcgugan** [comment]
We do have an api to [capture prints](https://textual.textualize.io/api/widget/#textual.widget.Widget.begin_capture_print). But theres not stdin per se in textual-web. The input comes from the network.

I'm not quite following what you want to do here. Can you give me a more concrete example of your use case?

**Comment by davidbrochart** [comment]
I'm trying to create a Jupyter widget for Textual, ideally I'd like to run a Textual App asynchronously (with `.run_async()`) in the Python kernel, so that the app is defined in the Python process where the user code runs. Then it's very similar to what `textual-web` does, `stdout` is sent to the browser where xtermjs displays a terminal, and xtermjs's input is sent to `stdin`. But `textual-web` launches a subprocess and interacts with `stdin`/`stdout`, and I'l like to do this in the same Python interpreter.

**Comment by willmcgugan** [comment]
Ah, I see. I think the best way to achieve that would be through the driver. The App constructor takes a reference to a `Driver` class. The default is to pick the appropriate driver, but you could supply one of your own.

You might want to modify the `LinuxDriver` to supply stdin / stdout of your own. Have a look at `WebDriver` which is used by textual-web.

**Comment by davidbrochart** [comment]
Thanks, that's exactly what I was looking for!
