### ISSUE TITLE
Help - How to use textual-web under Chinese network?

### ISSUE THREAD

**Issue by Tim-Cao** [Textualize/textual-web#42]
Given under Chinese network
When run textual-web
Then meet unable Unable to connect to Ganglion server.

![截屏2024-05-14 17 40 09](https://github.com/Textualize/textual-web/assets/52661397/1624d69e-32e1-4fd3-87aa-138615078244)

Would you mind providing some solution or idea? Thanks in advance!

**Comment by willmcgugan** [comment]
Can you connect to https://textual-web.io ?

**Comment by Tim-Cao** [comment]
> Can you connect to https://textual-web.io ?

Yes! 
![截屏2024-05-14 17 51 06](https://github.com/Textualize/textual-web/assets/52661397/0ef6cb1d-ede8-4484-b037-d2e9ba4f4d9e)

**Comment by willmcgugan** [comment]
That's promising! Means it it not firewalled.

If you add the `DEBUG=1` env var to the the `textual-web` command it may report extra information.

**Comment by Tim-Cao** [comment]
Error is here.
![截屏2024-05-14 20 34 31](https://github.com/Textualize/textual-web/assets/52661397/a618c87e-f489-4190-a806-c454c9dea290)

**Comment by willmcgugan** [comment]
Can you try this?

```python
python -m pip install certifi
```

**Comment by Tim-Cao** [comment]
Thanks for your help! @willmcgugan 
`brew update & brew upgrade` resolved my issue. It should be a problem from my machine.
