### ISSUE TITLE
Could it support images in the future?

### ISSUE THREAD

**Issue by mvsoom** [Textualize/textual-web#48]
Or in other words, which terminal is being emulated in the browser, and what kind of image support would it have?

**Comment by TomJGooding** [comment]
Textual support for images is on the roadmap - https://textual.textualize.io/FAQ/

Under the hood I think `textual-web` uses [xterm.js](https://github.com/xtermjs/xterm.js/), which includes an addon that supports images via the SIXEL and iTerm's inline image protocol.

**Comment by mvsoom** [comment]
That would be fantastic! Cheers.

**Comment by westurner** [comment]
- https://github.com/xtermjs/xterm.js/blob/master/addons/addon-image/src/SixelHandler.ts
